# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: monthly
repos:
- repo: https://github.com/fsfe/reuse-tool
  rev: v1.1.2
  hooks:
  - id: reuse
