# SPDX-FileCopyrightText: 2023 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-12
        preset:
          - cpp14
          - cpp17
          - cpp20
          - cpp23
        qt:
          - version: "5.15.2"
            requested: "5.15"
          - version: "6.3.2"  # Qt 6.3 is not an LTS version, so '6.3.*' always resolves to '6.3.2'
            requested: "6.3.*"

    steps:
      - name: Install Qt with options and default aqtversion
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: null # use whatever the default is
          modules: ${{ matrix.qt.modules }}
          version: ${{ matrix.qt.requested }}
          cache: true

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        uses: turtlesec-no/get-ninja@main

      - name: Make sure MSVC is found when Ninja generator is in use
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create Debug build directory
        run: mkdir build-debug

      - name: Configure Debug Build
        run: >
          cmake -S . -B ./build-debug -G Ninja --preset ${{ matrix.preset }}
          -DCMAKE_BUILD_TYPE=Debug
          -DBUILD_TESTING=ON
          -DKDALGORITHMS_BUILD_TEST=ON

      - name: Build Project (Debug)
        run: cmake --build ./build-debug

      - name: Run Debug tests
        run: ctest --test-dir ./build-debug -C Debug --output-on-failure

        # KDAlgorithms CI only matters (and builds) for the tests and since
        # the only value of a Release build is that maybe the compiler
        # does some optimization that breaks them we do both builds
        # in the same worker.
      - name: Create Release build directory
        run: mkdir build-release

      - name: Configure Release Build
        run: >
          cmake -S . -B ./build-release -G Ninja --preset ${{ matrix.preset }}
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTING=ON
          -DKDALGORITHMS_BUILD_TEST=ON

      - name: Build Project (Release)
        run: cmake --build ./build-release

      - name: Run Release tests
        run: ctest --test-dir ./build-release -C Release --output-on-failure

      - name: Read tests log when it fails
        uses: andstor/file-reader-action@v1
        if: ${{ failure() }}
        with:
          path: "./build/Testing/Temporary/LastTest.log"
